import 'package:meta/meta.dart';
import 'package:variable_font_generator/src/bindings/dart_identifiers.dart';
import 'package:variable_font_generator/src/generator/icon_axes.dart';
import 'package:variable_font_generator/src/generator/icon_font_generator.dart';

/// Thrown when two icons would produce the same Dart identifier.
final class IdentifierCollisionException implements Exception {
  /// Creates an exception naming both icons and the identifier they share.
  const IdentifierCollisionException({
    required this.identifier,
    required this.first,
    required this.second,
  });

  /// The identifier both icons wanted.
  final String identifier;

  /// The icon that claimed it first.
  final String first;

  /// The icon that collided with it.
  final String second;

  @override
  String toString() =>
      'Icons "$first" and "$second" both map to the Dart identifier '
      '"$identifier". Rename one of the source files.';
}

/// How the generated Dart file refers to the font.
///
/// Flutter resolves a font family declared by a package under the name
/// `packages/<package>/<family>`, and `TextStyle` adds that prefix itself when
/// it is given a package. So a font shipped inside a package has to name the
/// package, and one that lives in an application's own assets must not.
@immutable
final class FontReference {
  /// Creates a reference to a font shipped by [package].
  const FontReference.package({required this.family, required this.package});

  /// Creates a reference to a font declared in an application's own pubspec.
  const FontReference.application({required this.family}) : package = null;

  /// The font family name, which must match the `family:` in the pubspec.
  final String family;

  /// The package the font ships in, or `null` for an application-local font.
  final String? package;

  @override
  String toString() => package == null
      ? 'FontReference($family)'
      : 'FontReference($family in $package)';
}

/// Generates the Dart source of an icon class for a generated font.
///
/// Each icon becomes a `static const IconData` with the family and package
/// written out as string literals. That is deliberate: `IconData`'s parameters
/// are annotated `@mustBeConst`, and Flutter's release-mode icon tree shaker
/// only recognises literals, so pulling the family into a shared constant would
/// quietly stop the font being subset.
@immutable
final class FlutterBindingsGenerator {
  /// Creates a generator.
  const FlutterBindingsGenerator({
    required this.className,
    required this.font,
    this.axisSet = IconAxisSet.material,
    this.identifierStyle = IdentifierStyle.camelCase,
    this.mirroredInRightToLeft = const {},
    this.sourceDescription,
  });

  /// The name of the generated class.
  final String className;

  /// How the generated code refers to the font.
  final FontReference font;

  /// The axes the font offers, used to document the class.
  final IconAxisSet axisSet;

  /// How icon names become identifiers.
  final IdentifierStyle identifierStyle;

  /// Icon names that should be flipped in right-to-left layouts.
  ///
  /// Names are matched as they appear in the source files, before they are
  /// turned into identifiers.
  final Set<String> mirroredInRightToLeft;

  /// A line describing where the icons came from, included in the header.
  final String? sourceDescription;

  /// Generates the Dart source for [icons].
  ///
  /// Throws an [IdentifierCollisionException] when two icons would end up with
  /// the same name, which is worth failing on: the alternative is a duplicate
  /// member that either fails to compile or, if the two happen to differ in
  /// case only, silently shadows.
  String generate(List<GeneratedIcon> icons) {
    final identifiers = <String, String>{};
    final entries = <({String identifier, GeneratedIcon icon})>[];
    for (final icon in icons) {
      final identifier = toDartIdentifier(icon.name, style: identifierStyle);
      final existing = identifiers[identifier];
      if (existing != null) {
        throw IdentifierCollisionException(
          identifier: identifier,
          first: existing,
          second: icon.name,
        );
      }
      identifiers[identifier] = icon.name;
      entries.add((identifier: identifier, icon: icon));
    }
    entries.sort((a, b) => a.identifier.compareTo(b.identifier));

    final buffer = StringBuffer()
      ..writeln('// GENERATED BY package:variable_font_generator.')
      ..writeln('// Do not edit this file by hand.');
    if (sourceDescription != null) {
      buffer.writeln('// Source: $sourceDescription');
    }
    buffer
      ..writeln()
      ..writeln("import 'package:flutter/widgets.dart';")
      ..writeln()
      ..writeln('/// Icons from the `${font.family}` variable icon font.')
      ..writeln('///')
      ..writeln('/// Every icon responds to the axes the font was built with.')
      ..writeln('/// Pass them to [Icon] or set them on an [IconThemeData]:')
      ..writeln('///')
      ..writeln('/// ```dart')
      ..writeln('/// Icon(')
      ..writeln('///   $className.${entries.first.identifier},')
      ..writeln('///   size: 32,');
    for (final axis in axisSet.axes) {
      final parameter = _flutterParameterFor(axis.axis.tag);
      if (parameter != null) {
        buffer.writeln('///   $parameter: ${_exampleValue(axis)},');
      }
    }
    buffer
      ..writeln('/// )')
      ..writeln('/// ```')
      ..writeln('///')
      ..writeln('/// The axes, as Flutter names them:')
      ..writeln('///');
    for (final axis in axisSet.axes) {
      final parameter = _flutterParameterFor(axis.axis.tag);
      final name = parameter == null ? 'A variation' : '[Icon.$parameter]';
      buffer.writeln(
        '/// * $name — `${axis.axis.tag}`, from ${_number(axis.axis.minimum)} '
        'to ${_number(axis.axis.maximum)}, '
        'default ${_number(axis.axis.defaultValue)}.',
      );
    }
    buffer
      ..writeln('///')
      ..writeln(
        "/// A value outside an axis's range is clamped by the renderer, and "
        'an axis',
      )
      ..writeln(
        '/// the font does not have is ignored without complaint, so a '
        'mismatch shows',
      )
      ..writeln('/// up as an icon that simply does not change.')
      ..writeln('@staticIconProvider')
      ..writeln('abstract final class $className {');

    for (var index = 0; index < entries.length; index++) {
      final (:identifier, :icon) = entries[index];
      if (index > 0) {
        buffer.writeln();
      }
      buffer
        ..writeln('  /// The `${icon.name}` icon.')
        ..writeln('  static const IconData $identifier = IconData(')
        ..writeln('    0x${icon.codePoint.toRadixString(16)},')
        ..writeln("    fontFamily: '${font.family}',");
      if (font.package case final package?) {
        buffer.writeln("    fontPackage: '$package',");
      }
      if (mirroredInRightToLeft.contains(icon.name)) {
        buffer.writeln('    matchTextDirection: true,');
      }
      buffer.writeln('  );');
    }
    buffer.writeln('}');
    return buffer.toString();
  }

  /// The name of the `Icon` parameter that drives the given axis tag, if
  /// there is one.
  static String? _flutterParameterFor(String tag) => switch (tag) {
    'FILL' => 'fill',
    'wght' => 'weight',
    'GRAD' => 'grade',
    'opsz' => 'opticalSize',
    _ => null,
  };

  static String _exampleValue(IconAxis axis) =>
      _number(axis.controlsFill ? axis.axis.maximum : axis.axis.defaultValue);

  static String _number(double value) =>
      value == value.roundToDouble() && value.abs() < 1e15
      ? value.toStringAsFixed(1)
      : '$value';
}
