import 'package:meta/meta.dart';
import 'package:variable_font_generator/src/bindings/flutter_bindings.dart';

/// Writes the pubspec entries a Flutter project needs to load a generated font.
@immutable
final class FlutterPubspecGenerator {
  /// Creates a generator.
  const FlutterPubspecGenerator({required this.font, required this.assetPath});

  /// The font the pubspec should declare.
  final FontReference font;

  /// Where the font file sits, relative to the pubspec.
  ///
  /// A package must keep the file under `lib/`, because that is the only part
  /// of a package other projects can reach; an application can put it
  /// anywhere.
  final String assetPath;

  /// Just the `fonts:` block, for pasting into an existing pubspec.
  String fontsBlock({int indent = 2}) {
    final pad = ' ' * indent;
    return '${pad}fonts:\n'
        '$pad  - family: ${font.family}\n'
        '$pad    fonts:\n'
        '$pad      - asset: $assetPath\n';
  }

  /// A complete pubspec for a package that ships nothing but the font and its
  /// bindings.
  String package({
    required String name,
    required String description,
    String version = '1.0.0',
    String sdkConstraint = '^3.13.0',
    String flutterConstraint = '>=3.27.0',
    String? repository,
    List<String> topics = const [],
  }) {
    final buffer = StringBuffer()
      ..writeln('# GENERATED BY package:variable_font_generator.')
      ..writeln('# Do not edit this file by hand.')
      ..writeln('name: $name')
      ..writeln('description: $description')
      ..writeln('version: $version');
    if (repository != null) {
      buffer.writeln('repository: $repository');
    }
    if (topics.isNotEmpty) {
      buffer.writeln('topics:');
      for (final topic in topics) {
        buffer.writeln('  - $topic');
      }
    }
    buffer
      ..writeln()
      ..writeln('environment:')
      ..writeln('  sdk: $sdkConstraint')
      ..writeln("  flutter: '$flutterConstraint'")
      ..writeln()
      ..writeln('dependencies:')
      ..writeln('  flutter:')
      ..writeln('    sdk: flutter')
      ..writeln()
      ..writeln('flutter:')
      ..write(fontsBlock());
    return buffer.toString();
  }

  /// The instructions a person needs to use the font from their own project.
  String usageNotes({required String className, required String libraryPath}) {
    final buffer = StringBuffer()
      ..writeln('Add the font to your pubspec:')
      ..writeln()
      ..writeln('```yaml')
      ..writeln('flutter:')
      ..write(fontsBlock())
      ..writeln('```')
      ..writeln();
    if (font.package == null) {
      buffer.writeln(
        'The generated `IconData` values leave `fontPackage` unset, which is '
        'what an application-local font needs.',
      );
    } else {
      buffer.writeln(
        'The generated `IconData` values name `${font.package}` as their '
        'font package, so Flutter looks the family up as '
        '`packages/${font.package}/${font.family}`, which is exactly how the '
        'asset above is registered.',
      );
    }
    buffer
      ..writeln()
      ..writeln('Then use the icons:')
      ..writeln()
      ..writeln('```dart')
      ..writeln("import '$libraryPath';")
      ..writeln()
      ..writeln('Icon($className.house, size: 32, fill: 1, weight: 500);')
      ..writeln('```');
    return buffer.toString();
  }
}
