@Tags(['generated-package'])
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:variable_font_generator/variable_font_generator.dart';

import 'support/fixtures.dart';

/// Checks that the checked-in Flutter package still matches what the generator
/// produces from the same icons.
///
/// The package is checked in because the Flutter golden tests need something to
/// render, and a checked-in artefact that nothing verifies is an artefact that
/// quietly goes stale. Regenerate it with `tool/generate_lucide_package.sh`.
void main() {
  final repositoryRoot = p.normalize(p.join(Directory.current.path, '../..'));
  final packageDirectory = p.join(
    repositoryRoot,
    'packages',
    'lucide_variable_icons',
  );

  late BuildResult built;
  late Directory temporary;

  setUpAll(() {
    temporary = Directory.systemTemp.createTempSync('vfg-generated-');
    built = runBuild(
      BuildOptions(
        inputDirectory: fixtureDirectory,
        outputDirectory: p.join(temporary.path, 'lib'),
        family: 'LucideVariable',
        className: 'LucideIcons',
        extensionTypeName: 'LucideIconData',
        libraryFileName: 'lucide_variable_icons.dart',
        packageName: 'lucide_variable_icons',
        emitIndex: true,
        vendorId: 'VFG ',
        mirroredInRightToLeft: const {
          'arrow-right',
          'navigation',
          'navigation-2',
        },
        timestamp: fixtureTimestamp,
        names: const FontNames(
          family: 'LucideVariable',
          copyright:
              'Copyright (c) for portions of Lucide are held by Cole Bemis '
              '2013-2022 as part of Feather (MIT). All other copyright (c) for '
              'Lucide are held by Lucide Contributors 2022.',
          designer: 'Lucide Contributors',
          license: 'ISC',
          licenseUrl:
              'https://github.com/lucide-icons/lucide/blob/main/LICENSE',
          description:
              'A variable icon font generated by variable_font_generator.',
        ),
      ),
    );
  });

  tearDownAll(() => temporary.deleteSync(recursive: true));

  test('the checked-in font is what the generator produces today', () {
    expect(
      File(p.join(packageDirectory, 'lib', 'fonts', 'LucideVariable.ttf'))
          .readAsBytesSync(),
      File(built.fontPath).readAsBytesSync(),
      reason: 'Run tool/generate_lucide_package.sh',
    );
  });

  test('the checked-in bindings are what the generator produces today', () {
    expect(
      File(p.join(packageDirectory, 'lib', 'lucide_variable_icons.dart'))
          .readAsStringSync(),
      File(built.libraryPath!).readAsStringSync(),
      reason: 'Run tool/generate_lucide_package.sh',
    );
  });

  test('the checked-in index is what the generator produces today', () {
    expect(
      File(p.join(packageDirectory, 'lib', 'lucide_variable_icons_index.dart'))
          .readAsStringSync(),
      File(built.indexPath!).readAsStringSync(),
      reason: 'Run tool/generate_lucide_package.sh',
    );
  });

  test('the pubspec declares the font the bindings ask for', () {
    final pubspec = File(p.join(packageDirectory, 'pubspec.yaml'))
        .readAsStringSync();
    expect(pubspec, contains('family: LucideVariable'));
    expect(pubspec, contains('asset: lib/fonts/LucideVariable.ttf'));
    expect(
      pubspec,
      contains('name: lucide_variable_icons'),
      reason:
          'The generated IconData values name this package, and Flutter looks '
          'the family up as packages/<name>/<family>.',
    );
  });
}
